// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnPf4XcC8Jlmz0LDfPRs48UvxUQCYegMY',
    appId: '1:95397688650:web:1928e0326fc39e20eb3db3',
    messagingSenderId: '95397688650',
    projectId: 'edclass-a9119',
    authDomain: 'edclass-a9119.firebaseapp.com',
    storageBucket: 'edclass-a9119.firebasestorage.app',
    measurementId: 'G-X86XPF9SP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGbJA8Vsfsy6t9HaEyB2uuI5dWdaL7rAU',
    appId: '1:95397688650:android:818347834678d473eb3db3',
    messagingSenderId: '95397688650',
    projectId: 'edclass-a9119',
    storageBucket: 'edclass-a9119.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARGrFD5ElE4Z17k7mh82HhWMHYJhczV2U',
    appId: '1:95397688650:ios:b61dc9484d13e05feb3db3',
    messagingSenderId: '95397688650',
    projectId: 'edclass-a9119',
    storageBucket: 'edclass-a9119.firebasestorage.app',
    iosBundleId: 'com.example.educlassFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARGrFD5ElE4Z17k7mh82HhWMHYJhczV2U',
    appId: '1:95397688650:ios:b61dc9484d13e05feb3db3',
    messagingSenderId: '95397688650',
    projectId: 'edclass-a9119',
    storageBucket: 'edclass-a9119.firebasestorage.app',
    iosBundleId: 'com.example.educlassFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnPf4XcC8Jlmz0LDfPRs48UvxUQCYegMY',
    appId: '1:95397688650:web:68c42772e49e0acaeb3db3',
    messagingSenderId: '95397688650',
    projectId: 'edclass-a9119',
    authDomain: 'edclass-a9119.firebaseapp.com',
    storageBucket: 'edclass-a9119.firebasestorage.app',
    measurementId: 'G-W2RWFL1FCX',
  );
}
